//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apply()
        {
            this.Interviews = new HashSet<Interview>();
        }
    
        public int ApplicationID { get; set; }
        public int CanddidateID { get; set; }
        public int PositionID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Status { get; set; }
    
        public virtual Canddidate Canddidate { get; set; }
        public virtual JobPosition JobPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interviews { get; set; }
    }
}
