//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int InterviewID { get; set; }
        public int ApplicationID { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public string InterviewName { get; set; }
        public string Status { get; set; }
    
        public virtual Apply Apply { get; set; }
    }
}
